--drop table person if allready exists
--CREATE TABLE `person` (
--  `id` mediumint(8) unsigned NOT NULL,
--  `firstName` varchar(255) default NULL,
--  `lastName` varchar(255) default NULL,
--  `birthdate` varchar(255)
--) AUTO_INCREMENT=1;